apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: shyamcluster
  region: ap-south-1

nodeGroups:
   - name: node-group1
     desiredCapacity: 4
     instanceType: t2.micro
     ssh:
        publicKeyName: myclusterkey
   - name: node-group2
     minSize: 1
     maxSize: 3
     instancesDistribution:
       maxPrice: 0.010
       instanceTypes: ["t2.micro"] 
       onDemandBaseCapacity: 0
       onDemandPercentageAboveBaseCapacity: 50
       spotInstancePools: 2     
     ssh:
         publicKeyName: myclusterkey
