apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: sqlpassforwordpress.sal
  literals:
   - password=root
resources: 
  - secret.yml
  - mysqldep.yml
  - deploymentcreate.yml
